name: oggm-3dviz
channels:
  - conda-forge
dependencies:
  - contextily
  - ffmpeg
  - cartopy
  - imageio=2.27.0
  - ipywidgets
  - jupyterlab
  - netcdf4
  - python>=3.10
  - pyvista
  - pyvista-xarray
  - rioxarray
  - scikit-image
  - trame
  - trame-vtk
  - trame-vuetify
  - xarray
  - zarr
  - pip
  - pip:
    - imageio[ffmpeg]
